image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - ms-dotnettools.csharp
tasks:
  - name: Run dotnet backend
    command: gp sync-await envsetup && dotnet run --project ./api/Spawn.Demo.WebApi
    init: dotnet build ./api/Spawn.Demo.WebApi
  - name: Run react frontend
    command: gp sync-await envsetup && REACT_APP_SPAWN_DEMO_ENDPOINT=$(gp url 5050) yarn --cwd client/ start
    init: yarn --cwd client/
    openMode: split-right
  - name: Setup environment
    command: bash gitpod-start.sh
    openMode: tab-after
ports:
  - port: 3000
    onOpen: ignore
  - port: 5050
    onOpen: ignore
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: true
    addBadge: false