image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - ms-dotnettools.csharp
tasks:
  - name: Run dotnet backend
    command: dotnet run --project ./api/Spawn.Demo.WebApi
    init: dotnet build ./api/Spawn.Demo.WebApi && gp sync-await envsetup
  - name: Run react frontend
    command: REACT_APP_SPAWN_DEMO_ENDPOINT=$(gp url 5050) yarn --cwd client/ start
    init: yarn --cwd client/ && gp sync-await envsetup
    openMode: split-right
  - name: Setup environment
    command: bash gitpod-start.sh
    openMode: tab-after
ports:
  - port: 3000
  - port: 5050