CREATE TABLE organizations(
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(255),
    CreatedAt DATETIME DEFAULT GETDATE(),
);

CREATE TABLE accounts(
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    UserID VARCHAR(70),
    Email VARCHAR(255),
    CreatedAt DATETIME DEFAULT GETDATE(),
);