-- Script generated by Redgate Compare v1.11.1.9091

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.todo_list_id_seq...';END$$;
ALTER SEQUENCE public.todo_list_id_seq START 5000001;
SET check_function_bodies = true;
