name: Integration tests

on: workflow_dispatch

jobs:
  run_integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          echo "Installing spawnctl..."
          curl https://run.spawn.cc/install 2>/dev/null | sh > /dev/null 2>&1
          export PATH=$PATH:$HOME/.spawnctl/bin
          echo "spawnctl installed successfully"

          echo
          echo

          echo "Starting integration tests..."
          pushd api/Spawn.Demo.WebApi.Tests/
          dotnet test -l "console;verbosity=detailed"
          popd
        name: 'Run integration tests with Spawn databases'
        env:
          SPAWNCTL_ACCESS_TOKEN: ${{ secrets.SPAWNCTL_ACCESS_TOKEN }}
          ACCOUNT_IMAGE_NAME: spawn-demo-account-test
          TODO_IMAGE_NAME: spawn-demo-todo-test
          ACCOUNT_TAG_NAME: ${{ github.run_number }}
          TODO_TAG_NAME: ${{ github.run_number }}