name: Database migration test

on: workflow_dispatch

jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create todo data container
        id: create-todo-container
        uses: red-gate/spawn-ci-plugins/github/data-container/create@main
        with:
          dataImage: demo-todo:latest
          lifetime: '10m'
      - name: Create account data container
        id: create-account-container
        uses: red-gate/spawn-ci-plugins/github/data-container/create@main
        with:
          dataImage: demo-account:latest
          lifetime: '10m'
      - name: Run database migrations
        run: |
          ./migrate-db.sh $ACCOUNT_HOST $ACCOUNT_PORT $ACCOUNT_USERNAME $ACCOUNT_PASSWORD $TODO_HOST $TODO_PORT $TODO_USERNAME $TODO_PASSWORD

          echo "Successfully migrated both 'Todo' and 'Account' databases"
        env:
          TODO_HOST: ${{ steps.create-todo-container.outputs.dataContainerHost }}
          TODO_PORT: ${{ steps.create-todo-container.outputs.dataContainerPort }}
          TODO_USERNAME: ${{ steps.create-todo-container.outputs.dataContainerUsername }}
          TODO_PASSWORD: ${{ steps.create-todo-container.outputs.dataContainerPassword }}
          ACCOUNT_HOST: ${{ steps.create-account-container.outputs.dataContainerHost }}
          ACCOUNT_PORT: ${{ steps.create-account-container.outputs.dataContainerPort }}
          ACCOUNT_USERNAME: ${{ steps.create-account-container.outputs.dataContainerUsername }}
          ACCOUNT_PASSWORD: ${{ steps.create-account-container.outputs.dataContainerPassword }}
    env:
      SPAWNCTL_ACCESS_TOKEN: ${{ secrets.SPAWNCTL_ACCESS_TOKEN }}